import { TrustConstants } from "../jsonConfig/parser";

export class Constants {
  INIT_TRUST_VALUE!: number;
  DIRECT_TRUST_WEIGHT!: number;
  INDIRECT_TRUST_WEIGHT!: number;
  AUTHORITY_TRUST_WEIGHT!: number;
  LEADER_TRUST_WEIGHT!: number;
  TRUSTED_PEERS_WEIGHT!: number;
  OTHER_PEERS_WEIGHT!: number;
  PAST_CONTEXT_WEIGHT!: number;
  PAST_TRUSTEE_WEIGHT!: number;
  COMMUNICATION_TRUST_WEIGHT!: number;
  OBSERVATION_TRUST_WEIGHT!: number;
  PRESENT_TRUST_WEIGHT!: number;
  PAST_TRUST_WEIGHT!: number;
  STATE_OF_TRUSTOR_WEIGHT!: number;
  EXPLORED_AREA_WEIGHT!: number;
  WAS_OBJECT_FOUND_WEIGHT!: number;
  AVAILABLE_MEMBERS_WEIGHT!: number;
  TIME_LEFT_WEIGHT!: number;
  DATA_SENSITIVITY_WEIGHT!: number;
  CELL_SIZE!: number;
  constructor() {}

  setUp({
    INIT_TRUST_VALUE,
    DIRECT_TRUST_WEIGHT,
    INDIRECT_TRUST_WEIGHT,
    AUTHORITY_TRUST_WEIGHT,
    LEADER_TRUST_WEIGHT,
    TRUSTED_PEERS_WEIGHT,
    OTHER_PEERS_WEIGHT,
    PAST_CONTEXT_WEIGHT,
    PAST_TRUSTEE_WEIGHT,
    COMMUNICATION_TRUST_WEIGHT,
    OBSERVATION_TRUST_WEIGHT,
    PRESENT_TRUST_WEIGHT,
    PAST_TRUST_WEIGHT,
    STATE_OF_TRUSTOR_WEIGHT,
    EXPLORED_AREA_WEIGHT,
    WAS_OBJECT_FOUND_WEIGHT,
    AVAILABLE_MEMBERS_WEIGHT,
    TIME_LEFT_WEIGHT,
    DATA_SENSITIVITY_WEIGHT,
  }: TrustConstants) {
    this.INIT_TRUST_VALUE = INIT_TRUST_VALUE;
    this.DIRECT_TRUST_WEIGHT = DIRECT_TRUST_WEIGHT;
    this.INDIRECT_TRUST_WEIGHT = INDIRECT_TRUST_WEIGHT;
    this.AUTHORITY_TRUST_WEIGHT = AUTHORITY_TRUST_WEIGHT;
    this.LEADER_TRUST_WEIGHT = LEADER_TRUST_WEIGHT;
    this.TRUSTED_PEERS_WEIGHT = TRUSTED_PEERS_WEIGHT;
    this.OTHER_PEERS_WEIGHT = OTHER_PEERS_WEIGHT;
    this.PAST_CONTEXT_WEIGHT = PAST_CONTEXT_WEIGHT;
    this.PAST_TRUSTEE_WEIGHT = PAST_TRUSTEE_WEIGHT;
    this.COMMUNICATION_TRUST_WEIGHT = COMMUNICATION_TRUST_WEIGHT;
    this.OBSERVATION_TRUST_WEIGHT = OBSERVATION_TRUST_WEIGHT;
    this.PRESENT_TRUST_WEIGHT = PRESENT_TRUST_WEIGHT;
    this.PAST_TRUST_WEIGHT = PAST_TRUST_WEIGHT;
    this.STATE_OF_TRUSTOR_WEIGHT = STATE_OF_TRUSTOR_WEIGHT;
    this.EXPLORED_AREA_WEIGHT = EXPLORED_AREA_WEIGHT;
    this.WAS_OBJECT_FOUND_WEIGHT = WAS_OBJECT_FOUND_WEIGHT;
    this.AVAILABLE_MEMBERS_WEIGHT = AVAILABLE_MEMBERS_WEIGHT;
    this.TIME_LEFT_WEIGHT = TIME_LEFT_WEIGHT;
    this.DATA_SENSITIVITY_WEIGHT = DATA_SENSITIVITY_WEIGHT;
    this.CELL_SIZE =
      parseInt(document.getElementById("environmentCanvas")!.getAttribute("cell-size") ?? `${30}`, 10) || 30;
  }
}

export const ConstantsInstance = new Constants();
