// Define collision categories
const CATEGORY_SENSOR = 0x0001; // 1
const CATEGORY_COLLAPSIBLE = 0x0002; // 2
const CATEGORY_BORDER = 0x0003; // 2
const CATEGORY_DETECTABLE = 0x0004; // 4

export {
  CATEGORY_SENSOR,
  CATEGORY_COLLAPSIBLE,
  CATEGORY_DETECTABLE,
  CATEGORY_BORDER,
};
